openapi: 3.0.0
info:
  title: Project API
  description: API for managing project information
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://api.staging.example.com/v1
    description: Staging server

components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-API-KEY
      in: header

security:
  - apiKey: []

paths:
  /projects:
    get:
      summary: Retrieve a list of projects
      operationId: getProjects
      responses:
        '200':
          description: A list of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error

    post:
      summary: Create a new project
      operationId: createProject
      requestBody:
        description: Project object to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '201':
          description: The newly created project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

  /projects/{projectId}:
    get:
      summary: Retrieve a specific project by ID
      operationId: getProjectById
      parameters:
        - in: path
          name: projectId
          description: ID of the project to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The project with the specified ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error

    put:
      summary: Update an existing project
      operationId: updateProject
      parameters:
        - in: path
          name: projectId
          description: ID of the project to update
          required: true
          schema:
            type: string
      requestBody:
        description: Project object to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: The updated project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error

    delete:
      summary: Delete a project by ID
      operationId: deleteProject
      parameters:
        - in: path
          name: projectId
          description: ID of the project to delete
          required: true
          schema
